### ISSUE TITLE
Vector dataloader dimensions error

### ISSUE THREAD

**Issue by gecoombs** [antarctica/PolarRoute#198]
While developing a new dataloader as part of #197 I ran into a rather cryptic error referencing a mismatch in the number of data dimensions (traceback below). Possibly caused by the time coordinate in the data or the additional `crs` variable (neither of which are present for the SOSE data). Further testing highlighted a possible related issue with the `era5_wind` dataloader in the `add_mag_dir_to_xr` method on the 0.2.x branch.

config and data file: [vector_bug.zip](https://github.com/antarctica/PolarRoute/files/11834301/vector_bug.zip)

```
Traceback (most recent call last):
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/lib/python3.8/site-packages/xarray/core/variable.py", line 130, in as_variable
    obj = Variable(*obj)
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/lib/python3.8/site-packages/xarray/core/variable.py", line 366, in __init__
    self._dims = self._parse_dimensions(dims)
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/lib/python3.8/site-packages/xarray/core/variable.py", line 663, in _parse_dimensions
    raise ValueError(
ValueError: dimensions ('lat', 'long') must have the same length as the number of data dimensions, ndim=3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/bin/create_mesh", line 33, in <module>
    sys.exit(load_entry_point('polar-route', 'console_scripts', 'create_mesh')())
  File "/home/gecoomb/PycharmProjects/PolarRoute/polar_route/utils.py", line 231, in wrapper
    res = func(*args, **kwargs)
  File "/home/gecoomb/PycharmProjects/PolarRoute/polar_route/cli.py", line 97, in create_mesh_cli
    cg = MeshBuilder(config).build_environmental_mesh()
  File "/home/gecoomb/PycharmProjects/PolarRoute/polar_route/mesh_generation/mesh_builder.py", line 108, in __init__
    meta_data_list = self.initialize_meta_data(bounds, min_datapoints)
  File "/home/gecoomb/PycharmProjects/PolarRoute/polar_route/mesh_generation/mesh_builder.py", line 139, in initialize_meta_data
    loader = DataLoaderFactory().get_dataloader(
  File "/home/gecoomb/PycharmProjects/PolarRoute/polar_route/dataloaders/factory.py", line 108, in get_dataloader
    return data_loader(bounds, params)
  File "/home/gecoomb/PycharmProjects/PolarRoute/polar_route/dataloaders/vector/abstract_vector.py", line 80, in __init__
    self.data = self.add_mag_dir()
  File "/home/gecoomb/PycharmProjects/PolarRoute/polar_route/dataloaders/vector/abstract_vector.py", line 214, in add_mag_dir
    return add_mag_dir_to_xr(data, names)
  File "/home/gecoomb/PycharmProjects/PolarRoute/polar_route/dataloaders/vector/abstract_vector.py", line 198, in add_mag_dir_to_xr
    data = data.assign(
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 6080, in assign
    data.update(results)
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/lib/python3.8/site-packages/xarray/core/dataset.py", line 4946, in update
    merge_result = dataset_update_method(self, other)
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/lib/python3.8/site-packages/xarray/core/merge.py", line 1104, in dataset_update_method
    return merge_core(
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/lib/python3.8/site-packages/xarray/core/merge.py", line 755, in merge_core
    collected = collect_variables_and_indexes(aligned, indexes=indexes)
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/lib/python3.8/site-packages/xarray/core/merge.py", line 365, in collect_variables_and_indexes
    variable = as_variable(variable, name=name)
  File "/home/gecoomb/PycharmProjects/PolarRoute/venv/lib/python3.8/site-packages/xarray/core/variable.py", line 133, in as_variable
    raise error.__class__(
ValueError: Could not convert tuple of form (dims, data[, attrs, encoding]): (['lat', 'long'], array([[[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [0.06323867, 0.06605937, 0.03816936, ...,        nan,
                nan,        nan],
        ...,
        [       nan,        nan,        nan, ..., 0.08700264,
         0.11410018, 0.07368392],
        [       nan,        nan,        nan, ..., 0.10779726,
         0.091863  , 0.07630518],
        [       nan,        nan,        nan, ..., 0.17698299,
         0.09912356, 0.05991669]],

       [[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [0.05569246, 0.07170697, 0.04126173, ...,        nan,
                nan,        nan],
        ...,
        [       nan,        nan,        nan, ..., 0.10886064,
         0.14661241, 0.12139522],
        [       nan,        nan,        nan, ..., 0.13802974,
         0.13405331, 0.09587095],
        [       nan,        nan,        nan, ..., 0.19369445,
         0.12591922, 0.07078312]]])) to Variable.
```

**Comment by gecoombs** [comment]
This seems to be fixed after the changes made in #199
